[package]
name = "lynix_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15.0"
futures = "0.3"
chrono = { version = "0.4.23", features = ["serde"] }
log = "0"
postgres = "0.19.4" # To be used in the future, DO NOT REMOVE

[dependencies.mongodb]
version = "2.2.0"
default-features = false
features = ["async-std-runtime"]